services:
  service1:
    build: ./service1
    container_name: service1
    expose:
      - "8001"

  service2:
    build: ./service2
    container_name: service2
    expose:
      - "8002"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
